{% set version = "3.2.1" %}

package:
  name: rstr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rstr/rstr-{{ version }}.tar.gz
  sha256: c51924c626540eb626ed3eb8e5e6c1d2f2c73959d039c8ff61ee562baeb4e0ff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - rstr
  requires:
    - pip
    - mypy
    - pytest-cov
  commands:
    - pip check
    - mypy --strict -m rstr
    - pytest -vv --pyargs rstr --cov=rstr --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=94

about:
  home: https://github.com/leapfrogonline/rstr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Generate random strings in Python

extra:
  recipe-maintainers:
    - claymcleod
    - bollwyvl
